### ISSUE TITLE
Missing a hyphen

### ISSUE THREAD

**Issue by gelbbauch** [thegreatstorm/game-ansible#3]
https://github.com/thegreatstorm/game-ansible/blob/a002eecdcccdba2ebb6e98177dfb80d0469b742b/valheim/restart.yml#L5

**Comment by gelbbauch** [comment]
Actually just spacing is incorrect on lines 5, 7, and 8-end should be indented as a block

**Comment by thegreatstorm** [comment]
Fixed.
