### ISSUE TITLE
Adding Saved Game Data

### ISSUE THREAD

**Issue by philkrause** [thegreatstorm/game-ansible#5]
I wasn't sure where to put saved game data.

**Comment by philkrause** [comment]
My issue was not being able to view the opt/server/.config folder unless I was root user. aka sudo -i

**Comment by Dastano** [comment]
I don'T even have .config I need to create it myself? I want put people as admin.

**Comment by thegreatstorm** [comment]
I don't know what game your speaking of.

**Comment by Dastano** [comment]
He is talking about Valheim. I found my Config on Root Folder ^.^

**Comment by thegreatstorm** [comment]
https://youtu.be/xGO_JirjwUI
