### ISSUE TITLE
Valheim: Progress lost when stopping server 

### ISSUE THREAD

**Issue by ima9rd** [thegreatstorm/game-ansible#7]
It seems like the Valheim server is not gracefully stopped and the world is not saved prior to ending the task when running stop.yml. This causes loss of recent progress (unsure if it saves at all, haven't tested over a long period of time).

Steps to reproduce: 

1. Set up a server and run valheim/start.yml
2. Connect to the server as a player and place any structure. 
3. Log out and stop the server using valheim/stop.yml
4. Start the server again using valheim/start.yml

At this point, the structure placed previously is lost. This indicates that recent progress is lost when stopping a server and could result in some significant issues for some users.

**Comment by thegreatstorm** [comment]
There is currently know way that I know of to force save before shutting down the process.

**Comment by ima9rd** [comment]
I've submitted #8 to fix this issue. This changes the kill signal to SIGINT instead of SIGKILL, which causes the server to gracefully close and save progress. I've successfully tested this a few times now to confirm.

**Comment by thegreatstorm** [comment]
Updated! Thank you, sorry after the outages in Texas I been kind of awol.
